### ISSUE TITLE
社会网络分析_选题方向讨论

### ISSUE THREAD

**Issue by Mondseen** [Mondseen/Network#1]
#### 目标：
阳老师上课提到社会网络、社会资本，对应的学术领域的研究问题是什么（学科视角，找到上一级学科和子学科）？这个领域的文献发展脉络如何？这个领域的大牛有哪些？大牛的经典著作和主要思想有哪些？
 

#### 目前知道的大牛和代表作： 
林南 《社会资本》
马克.格兰诺维特  《社会与经济》《找工作》《镶嵌》
罗纳德.伯特（Ronald Burt） 《结构洞》
马修.杰克逊（Matthew O. Jackson） 《社会与经济网络》、《人类网络：社会位置决定命运》

**Comment by Mondseen** [comment]
# 社会网络和社会资本综述
## 社会网理论的发展
### 个人层次的社会网研究
- 格兰诺维特 ”弱关系“理论 1973
- 博特 ”结构洞“理论 1992
### 集体层次的社会网研究
社会网的探讨成为管理学与经济社会学之间的一座桥梁，美国管理学界已经认识到企业的运作绝非只是一连串理性计算的经济交易过程的串联而已，任何企业流程实际上都不只是制度安排，也都深深镶嵌在关系网络中；而交易行为也不尽然为制度所规范，人际关系依旧扮演着交易中的重要角色。
- 格兰诺维特 ”门槛理论“  1978 传播行为及新产品的传播
- 萨克森妮亚  产业集聚、产业区位 1994  
- 汉密尔顿   网络式企业 1989 
### 网络动态学
Watts    六度联结小世界  1998
## 社会资本理论及其衡量
社会资本分为微观、中观和宏观层次的社会资本。微观层次的社会资本发现个人通过建立社会关系获得资源，中观层次为结构分析，个人因其在社会结构中所处特定位置而对资源的可获得性，宏观层次关注的是团体、组织、社会、国家成员内部的互信状况。
- 林南 1982  个体层次的社会资本 （前述微观和中观）
- 布迪厄、科尔曼、普特南、福山   集体层次的社会资本  （前述 宏观）
布迪厄 1986 社会资本定义为一种通过对”体制化关系网络"的占有而获取的实际或潜在的资源的集合体
科尔曼 1988 社会资本定义为个人拥有的、表现为社会结构资源的财产
普特南 1995 社会资本定义为社会组织中那些表现为网络、规范和信任的特征
福山    1996  社会资本定义为社会或群体成员之间的信任普及程度
## 中国人的关系
- 费孝通  差序格局
- 黄光国 1988  人情与面子
 指出中国人差序格局由内而外有三层关系，而且每一层都适用于不同的交换规范，分别是情感性关系、工具性关系以及混合了情感和工具的混合性关系。

---

引用来源《社会学与中国社会》李培林

**Comment by Mondseen** [comment]
### 选题讨论
以上是目前我列的人物和大佬。从时间线上看，社会网络、社会资本这一支文献的研究热点大概是20年前。我个人感觉做某些大佬们个人的挖掘，不是特别有意思。结业作业指南里面提到学术分析容易发散，我就想着能不能找到一个有趣的点，结合学术分析和商业分析。
比如结合社会网络+专利，分析某一行业的专利的合作网络，比如生物医疗技术领域的专利合作网络。 
比如结合社会网络+产业+地理，分析某些产业及产业链条在城市空间上的网络分布。 

你们有什么好的想法么？

**Comment by sunshinecx** [comment]
关于产业 + 地理，我想到了微博上我关注的一个经济地理学的博主：牛津—小裁缝。真名：王晓阳。翻译了新版《牛津经济地理学手册》。近年来，产业集群，区域经济，粤港澳大湾区这些耳熟能详的词，都来自于经济地理学。分析哪个城市有发展潜力，适合年轻人去闯荡发展很多人都能说出几条。而经济地理学大约在二十多年前已经讨论了，《牛津经济地理学手册》在2005年中文版已经翻译了，2021年最新版正在路上。

**Comment by Junsong798** [comment]
看了看，感觉要学术+商业，那学术范围就得定小，比如“social capital"，social network是上位词，再做就大了。所以要么选题偏学术，做社会网络这一领域在社会学，经济学中的演变，要么一半一半，做社会资本的研究演变，分离出几种描述现实的框架，理论源流，怎么描述的，然后用一个或几个商业领域的数据来验证这些理论。最后呈现就像一篇小论文，introduction是纯综述，然后method收集一个行业的数据，做分析，data analysis，discussion这样。感觉要会做social network analysis?

**Comment by Mondseen** [comment]
### 上位词：社会网络、社会网络分析、社会资本 
#### 社会网络和社会资本的区别
社会网络本身不是社会资本；但它是社会资本的重要外生条件，社会关系网的特征是影响人们从中获取资源优劣的重要条件。
- 社会资本指网络参与者的信任关系与协作关系, 属于社会网络中的关系要素。
- 社会网络的另外一种要素是结构要素，指网络参与者的网络位置。
- 来源: 阳志平 人生资本阅读营
今天看了阳老师的人生资本阅读营，其实他已经把社会资本理论讲得差不多了，包括社会资本的研究演变，对学术大牛林南的挖掘。不过目前阳老师提的社会资本，主要是讨论“个人”的社会资本，也就是社会资本在“个人生活”中的应用。我们可以在阳老师提的社会资本拓展，把主体从“个人”换成“企业”，讨论社会网络分析在”企业组织“中的应用，但这个领域其实范围也还蛮广的。 

另外，选题也可以不局限于社会资本和社会网络分析，我觉得任何有兴趣值得挖掘的点都可以。但是这个”点“的颗粒度一定要细，可操作性强。

**Comment by Junsong798** [comment]
## 主题：特斯拉电池的产业结构和演变
我的理解是，大概了解特斯拉电池产业在**时间**上的发展脉络，随着时间，这个汽车的品牌和生产规模在**空间**上是怎么推进的。这背后可能又牵扯到不同的**变量关系**，是什么影响了汽车电池产业的发展。
## 学术脉络
学术脉络主要放在产业结构上，比如产业结构对应的学科，描述和预测产业结构（或者其他术语）的理论有哪些流派和大牛，各自提出了什么理论。
## 商业分析
商业分析具体看电池和特斯拉的发展，了解（锂？）电池的发展历史，有哪些时间空间节点不可忽视，从而与特斯拉的产业发展齐头并进。最后看这一套产业结构是否符合某些学术理论（比如某些指标用数据描述，比如看看能不能用社会网络分析描述一些结构；个人感觉难度不会小）。

**Comment by sunshinecx** [comment]
# 20210111 大作业第一次会议
- **参会人员：**  格格，我必须徒步穿越太阳系，陈鑫
- **时间：**  2021-01-11 20:30
- **初步确定选题范围：**

1. 学术分析：分析电动汽车的车用电池技术发展史，专利，大牛，转折点。
2. 学术分析：分析特斯拉自动驾驶技术发展史，以及汽车行业自动驾驶技术发展史。
3. 商业分析：分析特斯拉发展史。
4. 商业分析：重点特斯拉车用电池技术。专利，迭代，下一代电池技术储备。


- **时间，空间，变量关系**

1. 时间：发展史
2. 空间：产业链分布
3. 变量关系：电池技术不同派系的方案，如低端电动车的铅酸电池，特斯拉的锂电池技术，未来的固态电池技术。
4. 变量关系：无人驾驶技术的不同技术路径，如车载雷达技术，机器视觉技术。

- **注意事项**

1. 学术分析时，注意发掘不同大牛观点，甚至对立观点。便于交叉验证。
2. 专利分析时，注意有没有同期竞争技术被淘汰的情况。就像显示器技术发展史，日本企业押注的等离子显示技术最终败给了韩国企业的液晶显示技术。
3. 商业分析时，需呈现不同技术赛道的竞争者，分析不同公司创始人坚持的理念。美国研究自动驾驶汽车的公司很多，特斯拉，谷歌，苹果，还有很多初创公司（待查）。不仅有民用自动驾驶汽车，还有商用的自动驾驶卡车，有的矿山已经实现了矿车无人驾驶运输矿产。查询有自动驾驶测试牌照的公司。国外的传统汽车巨头也有电动车产品，丰田，本田，日产，大众，宝马，奔驰，保时捷等，只是没有特斯拉那么大的销量。
4. 国内的电动汽车公司也很多：初创公司有蔚来，小鹏，理想等；传统车企有比亚迪，上汽集团，北京汽车，长城汽车等，基本都有涉足。

- 大家需要在 GitHub 确定选题的截止时间，时间一到，必须结束资料搜索阶段，立即开始大作业。这个是往期课程被验证无数次的经验。
- 欢迎队友补充其他灵感。

----
- 2021-01-11
